[package]
name = "xtables_python"
version = "0.0.3"
edition = "2024"
description = "Python bindings for the xtables client."

[lib]
name = "xtables"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27", features = ["extension-module", "abi3-py39"] }
xtables_client = { path = "../rust" }
xtables_protobuf = { path = "../../proto", version = "0.0.3" }
